language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
# HHVM is not working due to an error with the iterator (?)
#  - hhvm
  - nightly

before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

install:
  - composer install
  - composer dump-autoload

after_success:
    - bash <(curl -s https://codecov.io/bash)